version: '2'
services:
  glab:
    build: .
    image: mortonprod/glab
    restart: unless-stopped
    volumes:
      - ./dist:/usr/src/app/dist/
      - ./xmlFiles:/usr/src/app/xmlFiles
      - ./views:/usr/src/app/views
    depends_on:
      - db
    ports:
      - "3001:3001"
  db: 
    image: mongo:latest
    restart: unless-stopped
    volumes:
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/data/db
    ports:
      - 27017